<?php

namespace Modules\Authentication\Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $permissions = [
            "(B) Penyesuaian Poin  di List Kepesertaan Kontes dan Riwayat Kepesertaan Kontes",
            "(B) Redeem Hadiah di List Kepesertaan Kontes dan Riwayat Kepesertaan Kontes",
            "(B) Ubah Hadiah di List Kepesertaan Kontes dan Riwayat Kepesertaan Kontes",
            "(B) Ekspor Penjualan Direct Distributor by Marketing per Tahun",
            "(B) Ekspor Penjualan Direct Retailer by Marketing per Tahun",
            "(B) Ekspor Rekap Indirect by Marketing per Tahun",
            "(B) Ekspor Rekap Transaksi Seluruh Toko Tahunan",
            "(B) Ekspor Wilayah yang Tidak Memiliki Tanaman",
            "(D) Tanggal Pendaftaran di Form Kontrak Kontes",
            "(B) Registrasi Kontes di Riwayat Kepesertaan",
            "(B) Ekspor Riwayat Direct Sales per Tanggal",
            "(B) Kontrak Kontes di List Pengajuan Kontes",
            "(B) Ekspor Riwayat Direct Sales per Tahun",
            "(B) Persetujuan Rencana Event (Manajemen)",
            "(B) Konfirmasi Permohonan Barang Promosi",
            "(B) Konfirmasi Barang Promosi Manajemen",
            "(B) Lanjutkan Draft Perubahan Subdealer",
            "(B) Persetujuan Rencana Event Manajemen",
            "(B) Perolehan Poin Marketing per Tahun",
            "(F) Pengajuan Pembatalan Diterima (12)",
            "(F) Rencana Disetujui (Supervisor) (3)",
            "(B) Ekspor Keseluruhan Penjualan Toko",
            "(B) Perolehan Fee Marketing per Tahun",
            "(B) Registrasi Peserta di List Kontes",
            "(F) Pengajuan Pembatalan Ditolak (13)",
            "(S) Penjualan dari dan ke Distributor",
            "(F) Rencana Disetujui (Support) (14)",
            "(F) Rencana Disetujui Manajemen (15)",
            "(F) Rencana Disetujui Marketing (16)",
            "(S) List Event Support & Manajemen",
            "(B) Ekspor Riwayat Indirect Sales",
            "(B) Export Riwayat Indirect Sales",
            "(D) Riwayat Penyelenggaraan Event",
            "(B) Batalkan Perubahan Subdealer",
            "(B) Ekspor Penjualan Detail Toko",
            "(B) Ekspor Sub-Dealer per Region",
            "(B) Export Wilayah Tanpa Tanaman",
            "(S) Penjualan Direct Per-Wilayah",
            "(B) Export Riwayat Direct Sales",
            "(B) Hapus Kontes di List Kontes",
            "(B) Jumlah Kios dengan 3 Petani",
            "(B) Tambah Aturan Fee Follow Up",
            "(D) Konfirmasi Pembatalan Event",
            "(F) Dikonfirmasi Supervisor (3)",
            "(S) List Konfirmasi Kontes Toko",
            "assign administrator permission",
            "create administrator permission",
            "delete administrator permission",
            "(B) Atur Muatan Barang Promosi",
            "(B) Cetak Surat Jalan (detail)",
            "(B) Tindak Lanjut Pickup Order",
            "(B) Ubah Kontes di List Kontes",
            "(F) Konfirmasi Pembatalan (11)",
            "(M) List Konfirmasi Registrasi",
            "(S) List Konfirmasi Registrasi",
            "(S) List Pengajuan Kontes Toko",
            "(S) Penyesuaian Indirect Sales",
            "(S) Riwayat Struktur Marketing",
            "(B) Atur Fee Cash dan Jabatan",
            "(B) Catat Kontrak Distributor",
            "(B) Ekspor Kios dengan Petani",
            "(B) Ekspor Kios per Marketing",
            "(B) Ekspor Transaksi Per Toko",
            "(B) Hapus Acuan Fee Marketing",
            "(B) Konfirmasi Indirect Sales",
            "(B) Konfirmasi kontrak kontes",
            "(B) Lanjutkan Draft Perubahan",
            "(B) Laporan Penyerahan Hadiah",
            "(B) Lihat Kontrak Distributor",
            "(B) Persetujuan Rencana Event",
            "(F) Laporan Penyerahan Hadiah",
            "(F) Pengajuan Pembatalan (11)",
            "(M) List Pengajuan Registrasi",
            "(S) Direct Sales Confirmation",
            "(S) Konfirmasi Indirect Sales",
            "(S) Lap. Penitipan Pembayaran",
            "(S) List Pengajuan Registrasi",
            "(S) Permohonan Barang Promosi",
            "(S) Riwayat Penerimaan Barang",
            "edit administrator permission",
            "show administrator permission",
            "(B) Ekspor Dealer per Region",
            "(B) Ekspor Seluruh List Toko",
            "(B) Export Daftar Sub-Dealer",
            "(B) Kalender Tanam per Tahun",
            "(B) Pembatalan Rencana Event",
            "(B) Riwayat Pembatalan Order",
            "(B) Sinkronisasi Poin Kontes",
            "(B) Ubah Acuan Fee Marketing",
            "(D) Konfirmasi Laporan Event",
            "(D) Konfirmasi Rencana Event",
            "(F) Detail Penerimaan Barang",
            "(F) Disetujui Manajemen (15)",
            "(F) Input Catatan Sub-Dealer",
            "(M) Perolehan Poin Marketing",
            "(P) Pengajuan Rencana Agenda",
            "(S) Kontrol Stok Distributor",
            "(S) Piutang Penjualan Direct",
            "(T) List Acuan Fee Marketing",
            "Duplikat Kontrak Distributor",
            "(B) Batalkan Dispatch Order",
            "(B) Export Penjualan Detail",
            "(B) Grafik Target Marketing",
            "(B) Hapus Metode Pembayaran",
            "(B) Hapus Penyerahan Hadiah",
            "(B) Proofing Indirect Sales",
            "(B) Tambah Kategori Tanaman",
            "(F) Input Catatan Marketing",
            "(F) Input Metode Pembayaran",
            "(F) Pembayaran Direct Sales",
            "(M) List Kepesertaan Kontes",
            "(P) Konfirmasi Order Detail",
            "(S) Daftar Agenda Marketing",
            "(S) Konfirmasi Extra Diskon",
            "(S) List Kepesertaan Kontes",
            "(S) List Redeem Kontes Toko",
            "(S) Pencapaian Produk Wajib",
            "(S) Proofing Indirect Sales",
            "(S) Template Dispatch Order",
            "Duplicate Planting Calendar",
            "Sinkronisasi Poin Marketing",
            "(B) Batalkan Dispath Order",
            "(B) Batalkan Pick Up Order",
            "(B) Grafik Lama Pembayaran",
            "(B) Hapus Kategori Tanaman",
            "(B) Hapus Penyesuaian Poin",
            "(B) Konfirmasi Ide promosi",
            "(B) Tambah Program Voucher",
            "(C) Custom Term Pembayaran",
            "(F) Konfirmasi Laporan (8)",
            "(F) Konfirmasi Rencana (2)",
            "(F) Konfirmasi Rencana (3)",
            "(F) Laporan Dikoreksi (10)",
            "(F) Penerbitan Surat Jalan",
            "(F) Rencana Disetujui (14)",
            "(S) Form Registrasi Kontes",
            "(S) Riwayat Indirect Sales",
            "(S) Template Collect Order",
            "(S) Template Pick Up Order",
            "Sinkronisasi Fee Marketing",
            "(B) Detail Analisis Group",
            "(B) Ekspor Area Marketing",
            "(B) Export Kalender Tanam",
            "(B) Export List Marketing",
            "(B) Terbitkan Surat Jalan",
            "(B) Ubah Kategori Tanaman",
            "(B) Ubah Status Marketing",
            "(B) Ubah Target Marketing",
            "(D) Lanjutkan Draft Event",
            "(D) Ubah Tingkat Keagenan",
            "(F) Form Penyesuaian Poin",
            "(F) Form Riwayat Struktur",
            "(F) Input Risalah Telepon",
            "(F) Pengajuan Laporan (8)",
            "(F) Rencana Dikoreksi (4)",
            "(M) Forecast & Pencapaian",
            "(S) Konfirmasi Sub-Dealer",
            "(S) Registrasi Sub-Dealer",
            "(T) List Acuan Fee Produk",
            "crud holding-organisation",
            "(B) Atur Status Limpahan",
            "(B) Batalkan Kredit Memo",
            "(B) Batalkan Surat Jalan",
            "(B) Blokir / Buka Blokir",
            "(B) Cetak Dispatch Order",
            "(B) Detail Tab Penjualan",
            "(D) Revisi Laporan Event",
            "(D) Revisi Rencana Event",
            "(F) Acuan Hari Pelunasan",
            "(F) Belum Dilaporkan (7)",
            "(F) Input Catatan Dealer",
            "(F) Laporan Diterima (9)",
            "(S) List Program Voucher",
            "(S) Perolehan Fee & Poin",
            "(S) Rekap Kalender Tanam",
            "(S) Riwayat Direct Sales",
            "(S) Template Surat Jalan",
            "(B) Acuan Benefit Grade",
            "(B) Cetak Dispath Order",
            "(B) Cetak Pick Up Order",
            "(B) Custom Kredit Limit",
            "(B) Kontrak Distributor",
            "(B) Tambah Acuan Blokir",
            "(B) Ubah Dispatch Order",
            "(D) Hapus Rencana Event",
            "(D) Lihat Laporan Event",
            "(D) Lihat Rencana Event",
            "(D) RevisiRencana Event",
            "(D) Tanggal Pendaftaran",
            "(F) Acuan Saran Grading",
            "(F) Rencana Ditolak (5)",
            "(F) Sedang Berjalan (6)",
            "(F) Sedang Diajukan (2)",
            "(S) Acuan Benefit Grade",
            "(S) Acuan Fee Marketing",
            "(S) List Dispatch Order",
            "(S) List Indirect Sales",
            "(B) Atur Fee Follow Up",
            "(B) Atur Tanggal Kirim",
            "(B) Batalkan Perubahan",
            "(B) Buat Pick Up Order",
            "(B) Detail Surat Jalan",
            "(B) Export Data Dealer",
            "(B) Hapus Acuan Blokir",
            "(B) Ubah Dispath Order",
            "(B) Ubah Pick Up Order",
            "(D) Buat Laporan Event",
            "(P) Pelaporan Indirect",
            "(S) Acuan Blokir Grade",
            "(S) Analisis Marketing",
            "(S) Daftar Distributor",
            "(S) Dealer Tidak Aktif",
            "(S) Detail Surat Jalan",
            "(S) Persetujuan Dealer",
            "(S) Peta Sebaran Login",
            "(S) Realisasi Forecast",
            "(T) Catatan Sub-Dealer",
            "(B) Cetak Surat Jalan",
            "(B) Detail Sub-Dealer",
            "(B) Detail Tab Produk",
            "(B) Format Batch Kios",
            "(B) Tambah Acuan Poin",
            "(B) Tambah Sub Region",
            "(F) Form Produk Wajib",
            "(S) Alamat pengiriman",
            "(S) Buat Direct Sales",
            "(S) Daftar Sub-Dealer",
            "(S) Konfirmasi Dealer",
            "(S) List Direct Order",
            "(S) Metode Pembayaran",
            "(S) Penjualan Bulanan",
            "(S) Registrasi Dealer",
            "(S) Sebaran Login All",
            "(S) Template Proforma",
            "(T) Catatan Marketing",
            "(B) Export Penjualan",
            "(B) Hapus Acuan Poin",
            "(B) Konfirmasi Order",
            "(B) Manage Pricelist",
            "(B) Penyesuaian Poin",
            "(B) Tambah Acuan Fee",
            "(B) Tambah Packaging",
            "(B) Telah Dibatalkan",
            "(B) Tutup Sub-Dealer",
            "(B) Ubah Waktu Event",
            "(F) Form Acuan Promo",
            "(F) Status Marketing",
            "(M) Kalender Tanaman",
            "(S) Grafik Statistik",
            "(S) Hadiah Merketing",
            "(S) Kalender Tanaman",
            "(S) Konfirmasi Order",
            "(S) List Kontes Toko",
            "(S) Status Marketing",
            "(S) Target Marketing",
            "(S) Template Invoice",
            "(T) List Surat Jalan",
            "(B) Hapus Acuan Fee",
            "(B) Hapus Packaging",
            "(B) Import Forecast",
            "(B) Retur Penjualan",
            "(B) Ubah Acuan Poin",
            "(B) Ubah Sub-Dealer",
            "(B)Export Penjualan",
            "(F) Upload file APK",
            "(M) Program Voucher",
            "(S) Konfirmasi Kios",
            "(S) Lama Pembayaran",
            "(S) Lama Pengiriman",
            "(S) Ranking Tanaman",
            "(T) Risalah Telepon",
            "dealer confirmation",
            "(B) Atur Marketing",
            "(B) Batalkan Order",
            "(B) Cetak Proforma",
            "(B) Hentikan Promo",
            "(B) Jadikan Dealer",
            "(B) Ubah Acuan Fee",
            "(B) Ubah Packaging",
            "(F) Pembayaran Fee",
            "(F) Tambah Tanaman",
            "(M) Analisis Group",
            "(M) Annual Meeting",
            "(M) Area Marketing",
            "(M) Data Marketing",
            "(M) Dispatch Order",
            "(M) Indirect Sales",
            "(S) Hari Pelunasan",
            "(S) Kalender Tanam",
            "(S) List Marketing",
            "(T) Catatan Dealer",
            "(T) List Packaging",
            "(B) Cetak Invoice",
            "(B) Detail Dealer",
            "(B) Hapus Grading",
            "(B) Hapus Tanaman",
            "(B) Histori Login",
            "(B) Import Alamat",
            "(B) Tambah Alamat",
            "(B) Tambah Produk",
            "(B) Tambah Region",
            "(B) Ubah Proforma",
            "(F) Benefit Grade",
            "(M) Master Kontes",
            "(M) Sebaran Login",
            "(S) Daftar Dealer",
            "(S) Master Kontes",
            "(S) Pick Up Order",
            "(S) Saran Grading",
            "(S) Tab Penjualan",
            "(T) List Proforma",
            "dealer submission",
            "marketing support",
            "(B) Atur Wilayah",
            "(B) Berangkatkan",
            "(B) Data Wilayah",
            "(B) Hapus Armada",
            "(B) Hapus Produk",
            "(B) Kunci Target",
            "(B) Serah terima",
            "(B) Submit Order",
            "(B) Tambah Order",
            "(B) Ubah Grading",
            "(B) Ubah Jabatan",
            "(B) Ubah Tanaman",
            "(F) Data Grading",
            "(M) Direct Sales",
            "(M) Master Event",
            "(S) Batasan Hari",
            "(S) Harga Produk",
            "(S) Produk Wajib",
            "crud sales order",
            "event submission",
            "(B) Atur Muatan",
            "(B) Export Kios",
            "(B) Export Toko",
            "(B) Grup Produk",
            "(B) Hapus Acuan",
            "(B) Hapus Order",
            "(B) Hapus Promo",
            "(B) Muat Barang",
            "(B) Redeem Poin",
            "(B) Seeder Kios",
            "(B) Ubah Armada",
            "(B) Ubah Dealer",
            "(B) Ubah Produk",
            "(F) Atur Muatan",
            "(F) Atur Pickup",
            "(F) Form Armada",
            "(M) Acuan Promo",
            "(M) Ekspor Data",
            "(M) Ide Promosi",
            "(S) Atur Muatan",
            "(S) Daftar Area",
            "(S) Daftar Kios",
            "(S) Surat Jalan",
            "(T) List Produk",
            "crud data acuan",
            "dealer inactive",
            "see own profile",
            "(B) Buat Order",
            "(B) Hapus Kios",
            "(B) Konfirmasi",
            "(B) Lepas Muat",
            "(B) Stock Sync",
            "(B) Ubah Acuan",
            "(B) Ubah Order",
            "(D) Ubah Grade",
            "(M) Cek Muatan",
            "(M) Data Acuan",
            "(M) Statistika",
            "(M) Sub Dealer",
            "(S) Acuan Poin",
            "(S) Fee Produk",
            "(S) List Event",
            "(S) Pencapaian",
            "(S) Tab Produk",
            "dealer grading",
            "(B) Asal Poin",
            "(B) Atur Area",
            "(B) Follow Up",
            "(B) Ubah Kios",
            "(F) Draft (1)",
            "(M) APK Share",
            "(M) List Task",
            "(M) List Toko",
            "approve event",
            "Assistant MDM",
            "crud personel",
            "(B) Asal Fee",
            "(B) Sync Fee",
            "(M) Template",
            "(S) Forecast",
            "(S) Tab Toko",
            "crud holding",
            "(S) Tanaman",
            "crud dealer",
            "(M) Dealer",
            "(M) Gudang",
            "(S) Produk",
            "crud store",
            "event test",
            "supervisor",
            "(B) Aktif",
            "(B) Hapus",
            "(M) Event",
            "crud user",
            "(M) Kios",
            "MDM",
            "RMC",
            "MM",
            "RM",
        ];

        foreach ($permissions as $permission) {
            Permission::create([
                "name" => $permission
            ]);
        }
    }
}
