<?php

namespace Modules\DataAcuan\Database\Seeders;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProformaReceiptTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $proforma = [
            [
                "id" => 1,
                "siup" => "054/12-03/PK/II/2018",
                "npwp" => "02.777.680.6-545.000",
                "tdp" => null,
                "ho" => null,
                "nib" => "0220004161981",
                "payment_info" => `<p><strong>Cara Pembayaran: </strong></p>\n\n<ol>\n\t<li>Pembayaran dengan Cek dan Giro dianggap sah bila telah dapat diuangkan</li>\n\t<li>Pembayaran dapat ditransfer melalui Rekening:</li>\n</ol>\n\n<ul style=\\"margin-left:40px\\">\n\t<li>Bank <strong>Mandiri</strong></li>\n</ul>\n\n<ul style=\\"list-style-type:none; margin-left:40px\\">\n\t<li>No. Rekening : <strong>1370036002000</strong></li>\n\t<li>Atas Nama : <strong>CV JAVAMAS AGROPHOS</strong></li>\n</ul>\n\n<ul style=\\"margin-left:40px\\">\n\t<li>Bank <strong>BCA</strong></li>\n</ul>\n\n<ul style=\\"list-style-type:none; margin-left:40px\\">\n\t<li>No. Rekening : <strong>8950600200</strong></li>\n\t<li>Atas Nama : <strong>CV JAVAMAS AGROPHOS</strong></li>\n</ul>`,
                "company_name" => "",
                "company_address" => "Jl. Raya Sambipitu-Nglipar Km 8.3, Kedung Keris, Nglipar, Gunungkidul, Yogyakarta",
                "company_telephone" => "(0274) 6789 887",
                "company_hp" => "+6278 8999 87890",
                "company_email" => "office@javamas.com",
                "logo_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/84c43e06-b440-43ea-a992-c7adbe3fe53a.png",
                "image_header_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/0d4bd68b-7a8f-4790-8209-0c962f9995e7.png",
                "iso" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/e2fa884c-0e8c-45c7-aede-ab61ce51e68e.png",
                "image_footer_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/853f0d4d-7fe2-4e6a-97ba-26f70cc7eaea.png",
                "note_receving" => null,
                "note_sop" => "<p>Harga tersebut di atas tidak termasuk biaya ekspedisi dan biaya bongkar/menurunkan barang.</p>\n\n<p>Sesuai <strong>SOP CV JAVAMAS AGROPHOS</strong> melarang Marketing kami membawa / menjual barang langsung Dealer kami ke petani / toko lain. Bila Dealer memberikan barang ke Marketing kami, bukan tanggung jawab kami dan sepenuhnya menjadi tanggung jawab Dealer.</p>",
                "note" => null,
                "receipt_for" => "1",
                "confirmed_by" => "b9715cf5-f93e-47ee-9af1-2d170047b526",
                "created_at" => "2022-04-08 13:06:36",
                "updated_at" => "2024-01-31 09:10:49",
                "deleted_at" => null,
            ],
            [
                "id" => 2,
                "siup" => "054/12-03/PK/II/2018",
                "npwp" => "02.777.680.6-545.000",
                "tdp" => null,
                "ho" => null,
                "nib" => "0220004161981",
                "payment_info" => `<p><strong>Cara Pembayaran: </strong></p>\n\n<ol>\n\t<li>Pembayaran dengan Cek dan Giro dianggap sah bila telah dapat diuangkan</li>\n\t<li>Pembayaran dapat ditransfer melalui Rekening:</li>\n</ol>\n\n<ul style=\\"margin-left:40px\\">\n\t<li>Bank <strong>Mandiri</strong></li>\n</ul>\n\n<ul style=\\"list-style-type:none; margin-left:40px\\">\n\t<li>No. Rekening : <strong>1370036002000</strong></li>\n\t<li>Atas Nama : <strong>CV JAVAMAS AGROPHOS</strong></li>\n</ul>\n\n<ul style=\\"margin-left:40px\\">\n\t<li>Bank <strong>BCA</strong></li>\n</ul>\n\n<ul style=\\"list-style-type:none; margin-left:40px\\">\n\t<li>No. Rekening : <strong>8950600200</strong></li>\n\t<li>Atas Nama : <strong>CV JAVAMAS AGROPHOS</strong></li>\n</ul>`,
                "company_name" => "",
                "company_address" => "Jl. Raya Sambipitu-Nglipar Km 8.3, Kedung Keris, Nglipar, Gunungkidul, Yogyakarta",
                "company_telephone" => "0274 2910999",
                "company_hp" => "+62852 9000 9000",
                "company_email" => "office@javamas.com",
                "logo_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/5d1b3d25-c0b3-4b4f-8ad0-0d99c2450f01.png",
                "image_header_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/624bc937-7f8d-483a-a20d-e11eb82bf635.png",
                "iso" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/a793810f-1eb5-4028-8f3f-d76c864a8233.png",
                "image_footer_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/c10e010f-429a-4381-9ea5-1e09616edaf2.png",
                "note_receving" => "<p>Barang yang telah diterima sudah sesuai dengan Surat Jalan:",
                "note_sop" => "<p>Harga tersebut di atas tidak termasuk biaya ekspedisi dan biaya bongkar/menurunkan barang.</p>\n\n<p>Sesuai <strong>SOP CV JAVAMAS AGROPHOS</strong> melarang Marketing kami membawa / menjual barang langsung Dealer kami ke petani / toko lain. Bila Dealer memberikan barang ke Marketing kami, bukan tanggung jawab kami dan sepenuhnya menjadi tanggung jawab Dealer.</p>",
                "note" => null,
                "receipt_for" => "2",
                "confirmed_by" => "b9715cf5-f93e-47ee-9af1-2d170047b526",
                "created_at" => "2022-04-08 13:06:36",
                "updated_at" => "2024-02-01 17:26:16",
                "deleted_at" => null,
            ],
            [
                "id" => 3,
                "siup" => "054/12-03/PK/II/2018",
                "npwp" => "02.777.680.6-545.000",
                "tdp" => null,
                "ho" => null,
                "nib" => "0220004161981",
                "payment_info" => null,
                "company_name" => "Javamas Agrophos",
                "company_address" => "Jl. Raya Sambipitu-Nglipar Km 8.3, Kedung Keris, Nglipar, Gunungkidul, Yogyakarta",
                "company_telephone" => "0274 2910999",
                "company_hp" => "+62852 9000 9000",
                "company_email" => "office@javamas.com",
                "logo_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/947fbc66-7771-4dc9-aa6c-cabf8a4e74e4.png",
                "image_header_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/26da133d-1b59-4222-bbe4-3adf6b4a41b9.png",
                "iso" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/6be46f97-f290-419a-a280-20f1bd983fc9.png",
                "image_footer_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/2b0a7f2c-4a15-4a6d-b476-dbe786a2f1de.png",
                "note_receving" => null,
                "note_sop" => null,
                "note" => null,
                "receipt_for" => "3",
                "confirmed_by" => "b9715cf5-f93e-47ee-9af1-2d170047b526",
                "created_at" => "2022-04-08 13:06:36",
                "updated_at" => "2024-01-31 10:01:36",
                "deleted_at" => null,
            ],
            [
                "id" => 4,
                "siup" => "054/12-03/PK/II/2018",
                "npwp" => "02.777.680.6-545.000",
                "tdp" => null,
                "ho" => null,
                "nib" => "0220004161981",
                "payment_info" => null,
                "company_name" => "Javamas Agrophos",
                "company_address" => "Jl. Raya Sambipitu-Nglipar Km 8.3, Kedung Keris, Nglipar, Gunungkidul, Yogyakarta",
                "company_telephone" => "0274 2910999",
                "company_hp" => "+62852 9000 9000",
                "company_email" => "office@javamas.com",
                "logo_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/ab8d1295-7dde-46e4-b861-efabbffac78e.png",
                "image_header_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/eda88786-1af0-4431-be23-2044358a866b.png",
                "iso" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/d08827f1-f777-4f11-a990-a70491ff6ea4.png",
                "image_footer_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/54d8b912-bc9b-48d1-bd43-b3512de43a27.png",
                "note_receving" => "<p>Barang-barang tersebut di atas sudah dicek, dihitung, dan diterima dengan kondisi yang baik dan benar oleh:</p>",
                "note_sop" => "<p>Segala kerusakan dan kehilangan pada saat pengiriman menjadi tanggung jawab Armada / Supir setelah diterima dengan bukti tanda tangan di bawah. Dengan ditanda tanganinya surat jalan ini, maka surat jalan ini dipakai sekaligus sebagai tanda terima barang.</p>",
                "note" => null,
                "receipt_for" => "4",
                "confirmed_by" => "b9715cf5-f93e-47ee-9af1-2d170047b526",
                "created_at" => "2022-04-08 13:06:36",
                "updated_at" => "2024-01-31 10:31:24",
                "deleted_at" => null,
            ],
            [
                "id" => 5,
                "siup" => null,
                "npwp" => null,
                "tdp" => null,
                "ho" => null,
                "nib" => null,
                "payment_info" => null,
                "company_name" => "Javamas Agrophos",
                "company_address" => "Jl. Raya Sambipitu-Nglipar Km 8.3, Kedung Keris, Nglipar, Gunungkidul, Yogyakarta",
                "company_telephone" => "0274 2910999",
                "company_hp" => "+62852 9000 9000",
                "company_email" => "office@javamas.com",
                "logo_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/bacb874b-e62c-48d7-8f82-4987f482c964.png",
                "image_header_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/49a7a210-826b-4255-a10e-625d4dde4bd9.png",
                "iso" => null,
                "image_footer_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/5a30fac8-d106-4fc7-861b-eff94ff72467.png",
                "note_receving" => "",
                "note_sop" => "",
                "note" => null,
                "receipt_for" => "5",
                "confirmed_by" => "b9715cf5-f93e-47ee-9af1-2d170047b526",
                "created_at" => "2022-04-08 13:06:36",
                "updated_at" => "2024-01-31 13:20:50",
                "deleted_at" => null,
            ],
            [
                "id" => 6,
                "siup" => null,
                "npwp" => null,
                "tdp" => null,
                "ho" => null,
                "nib" => null,
                "payment_info" => null,
                "company_name" => "Javamas Agrophos",
                "company_address" => "Jl. Raya Sambipitu-Nglipar Km 8.3, Kedung Keris, Nglipar, Gunungkidul, Yogyakarta",
                "company_telephone" => "0274 2910999",
                "company_hp" => "+62852 9000 9000",
                "company_email" => "office@javamas.com",
                "logo_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset+template+pdf/Logo+cetak.png",
                "image_header_link" => "",
                "iso" => null,
                "image_footer_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset+template+pdf/Title.png",
                "note_receving" => "",
                "note_sop" => "",
                "note" => null,
                "receipt_for" => "6",
                "confirmed_by" => "b9715cf5-f93e-47ee-9af1-2d170047b526",
                "created_at" => "2022-06-13 14:57:43",
                "updated_at" => "2022-06-13 14:57:43",
                "deleted_at" => null,
            ],
            [
                "id" => 7,
                "siup" => "054/12-03/PK/II/2018",
                "npwp" => "02.777.680.6-545.000",
                "tdp" => null,
                "ho" => null,
                "nib" => "0220004161981",
                "payment_info" => "<p>qwqwqwq</p>",
                "company_name" => "",
                "company_address" => "Jl. Raya Sambipitu-Nglipar Km 8.3, Kedung Keris, Nglipar, Gunungkidul, Yogyakarta",
                "company_telephone" => "0274 2910999",
                "company_hp" => "+62852 9000 9000",
                "company_email" => "office@javamas.com",
                "logo_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/e5f85766-e10c-4cc4-8f2a-5c071de4a7c9.png",
                "image_header_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/3308a05a-278c-4c95-9822-b7b50596e828.png",
                "iso" => null,
                "image_footer_link" => "https://javamas-bucket.s3.ap-southeast-1.amazonaws.com/public/nota/asset template pdf/c755473f-59a8-4d27-974a-7ee8787fa173.png",
                "note_receving" => "<p>Barang - barang tersebut diatas sudah dicek, dihitung, dan telah diterima dengan kondisi yang baik dan benar oleh :</p>",
                "note_sop" => "<p>Segala kerusakan dan kehilangan pada saat pengiriman menjadi tanggung jawab Armada / Supir setelah diterima dengan bukti tandatangan dibawah. Dengan ditandatanganinya surat jalan ini, maka surat jalan ini dipakai sekaligus sebagai tanda terima barang.</p>",
                "note" => null,
                "receipt_for" => "7",
                "confirmed_by" => "b9715cf5-f93e-47ee-9af1-2d170047b526",
                "created_at" => "2022-06-13 14:57:43",
                "updated_at" => "2024-01-31 14:02:55",
                "deleted_at" => null,
            ],
        ];
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('proforma_receipts')->truncate();
        foreach ($proforma as $value) {
            DB::table('proforma_receipts')->insert($value);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
